Iter9
freepaddler/yap-metrics pull request #11
Opened 2023-06-26 20:25 UTC by freepaddler

2023-06-29 21:47 UTC, valentinsoe requested changes
Спасибо за работу!
Я написал ряд замечаний(в основном связанных с оформлением кода).

Еще у нас не было задачи сохранять метрики в "реальном" времени, только периодически. В текущей схеме с hook мне не очень нравится момент связанный с тем, что memstorage передает всего себя в hook, а также тип и имя метрики.
Вместо того чтобы передать объект метрика с его текущим состоянием.

2023-06-29 21:47 UTC, valentinsoe commented on internal/store/file/file.go
> +	sw   bool
Из названия поля мне не очень понятно зачем оно(с учетом того, что оно не используется)

2023-06-29 21:51 UTC, valentinsoe commented on internal/store/file/file.go
> +	switch m.Type {
С такой работой с файлом(обновление в "реальном" времени) есть одно существенная проблема.
Мы из потенциально большого количества потоков пишем в один файл. Что в общем случае небезопасно.

Если бы мы только "текущее" состояние раз в X секунд записывали бы в файл из одного потока - то беспокоиться о потоко-безопасности бы не пришлось.

2023-06-29 23:26 UTC, freepaddler commented on internal/agent/reporter/http.go
> +				logger.Log.Warn().Err(err).Msgf("unable to marshal JSON: %s", body)
точно, спасибо, исправил

2023-06-29 23:45 UTC, freepaddler commented on internal/agent/reporter/http.go
> +			var buf bytes.Buffer
done

2023-06-29 23:55 UTC, freepaddler commented on internal/logger/logger.go
> +	zerolog.SetGlobalLevel(v)
fixed

2023-06-29 23:56 UTC, freepaddler commented on internal/server/compress/compress.go
> +func GzipMiddleware(next http.Handler) http.Handler {
да, я рассматривал этот вариант, но было интереснее (и логичнее с точки зрения курса) сделать отдельно. я бы оставил, если нет возражений

2023-06-29 23:58 UTC, freepaddler commented on internal/server/compress/compress.go
> +		rw := w
принято

2023-06-30 00:10 UTC, freepaddler commented on internal/store/file/file.go
> +	sw   bool
ой, артефакт :), убрал

2023-06-30 00:24 UTC, freepaddler commented on internal/store/memory/memory.go
> +	ms.updateHook(name, models.Gauge)
да, поправил, это связано с требованием что delta и value - указатели в модели метрики. это выносит мне мозг (вопроса "зачем" указатели - не возникает, именно для этого же)

2023-06-30 00:48 UTC, freepaddler commented on cmd/server/main.go
> +	if err != nil {
fixed

2023-06-30 01:02 UTC, freepaddler commented on internal/store/file/file.go
> +	switch m.Type {
эммм, не очень понял почему не было задачи сохранения метрики в реальном времени, в задаче же сказано:

`Флаг -i, переменная окружения STORE_INTERVAL — интервал времени в секундах, по истечении которого текущие показания сервера сохраняются на диск (по умолчанию 300 секунд, значение 0 делает запись синхронной).`

я вот слово "синхронно" увидел - и сделал.
про потоко-безопасность я понимаю, но мы же вроде пока до этого не дошли :)
мне лучше убрать эту функциональность или так оставить пока?
просто не понимаю как обеспечить потоко-безопасность текущими, полученными на курсе темами (ни мьютексов, горутин с каналами)

2023-06-30 01:19 UTC, freepaddler commented on cmd/server/main.go
> +	ticker := 1
fixed

2023-07-03 14:05 UTC, freepaddler commented on internal/server/compress/compress.go
> +func GzipMiddleware(next http.Handler) http.Handler {
заменил на встроенный mw

2023-07-03 14:06 UTC, freepaddler commented on internal/store/file/file.go
> +	switch m.Type {
добавил mutex

2023-07-03 17:18 UTC, valentinsoe commented on cmd/server/main.go
> +	if conf.UseFileStorage {
В порядке занудства(исправлять необязательно). Я бы все это выделил в отдельную функцию хотя бы

2023-07-03 17:48 UTC, valentinsoe approved these changes
Спасибо за исправления!

Теперь появился небольшой нюанс со сжатием и установкой хедера.
В остальном замечания не критичный. Работу применяю. Если есть желание еще что-то обсудить, можно написать в пачке/PRе.

2023-07-03 17:48 UTC, valentinsoe commented on cmd/server/main.go
> +	//logger.Log.Debug().Msg("Starting file storage loop...")
Предлагаю коммент удалить:)

2023-07-03 17:48 UTC, valentinsoe commented on internal/agent/reporter/http.go
> +	m := r.s.Snapshot()
Занудство - m, r, s - очень много однобуквенных переменных в одном месте - сложно читать

2023-07-03 17:48 UTC, valentinsoe commented on internal/agent/reporter/http.go
> +				r.unreported(&v)
Может лучше обернуть это в функцию, возвращать ошибку и в ее случае делать r.unreported?
А то 4 вызова в одной функции кажется многовато.

2023-07-03 17:48 UTC, valentinsoe commented on internal/agent/reporter/http.go
> +		logger.Log.Error().Err(err).Msg("unable to compress body, sending uncompressed")
В таком случае надо header убирать. Клиент все равно сломается, если получит header content-encoding = gzip и несжатое тело ответа.
Если сломалось сжатие, можно просто вернуть 500. Это явно какая-то "системная" ошибка.

2023-07-03 17:48 UTC, valentinsoe commented on internal/server/config/config.go
> +	if len(c.FileStoragePath) > 0 {
Более привычным было бы проверить на != "", чем через длину.

2023-07-03 17:48 UTC, valentinsoe commented on internal/store/file/file.go
> +	ticker := 1
Рекомендую перейти на более аккуратный вариант:
<- time.Ticker()

2023-07-03 17:48 UTC, valentinsoe commented on internal/agent/reporter/http.go
> +	// для gauge: восстанавливать из снапшота, если не появилось нового значения
Для нашего задания это некоторое усложнение.
На мой взгляд без сложной многопоточности эта задача плохо решается

2023-07-04 00:52 UTC, freepaddler commented on cmd/server/main.go
> +	if conf.UseFileStorage {
выделил - написал в TODO вопрос, можно здесь обсудить или в следующем 1-1

2023-07-04 01:14 UTC, freepaddler commented on internal/agent/reporter/http.go
> +	// для gauge: восстанавливать из снапшота, если не появилось нового значения
ну, учитывая, что у нас на текущий момент сбор метрик и репортинг работают последовательно, то сделанные изменения (очищаем стор, если не удалось отправить метрику, то восстанавливаем её в сторе) в принципе логичны. при добавлении многопоточности исправления будут в методах интерфейса и не должны затронуть репортер

2023-07-04 01:21 UTC, freepaddler commented on internal/agent/reporter/http.go
> +		logger.Log.Error().Err(err).Msg("unable to compress body, sending uncompressed")
ой, да. случай если сжатие ломается я обрабатываю, добавил проверку, что сжатие прошо успешно и только в этом случае устанавливается content-encoding

2023-07-04 01:27 UTC, freepaddler commented on internal/agent/reporter/http.go
> +	m := r.s.Snapshot()
согласен,  поправил именование полей структуры reporter

2023-07-04 01:34 UTC, freepaddler commented on internal/store/file/file.go
> +	ticker := 1
done

2023-07-04 01:53 UTC, freepaddler commented on internal/agent/reporter/http.go
> +				r.unreported(&v)
ну, я чуточку по-другому сделал, но читаемость улучшилась и множества вызовов удалось избежать, правда и функцию убрал :) не знаю, стоило ли...

2023-07-04 01:53 UTC, freepaddler commented
Я вроде все поправил, на каждое исправление отдельным коммитом, чтобы было проще смотреть если что

2023-07-04 14:19 UTC, merged