Iter5
freepaddler/yap-metrics pull request #7
Opened 2023-06-06 14:16 UTC by freepaddler

2023-06-07 11:39 UTC, valentinsoe requested changes
Спасибо за быструю отправку и соблюдение конвенции именования!
Рекомендую разделить все-таки код на инициализацию приложения(оставить ее в пакете main) и реализацию(унести в пакет internal) и разделить по функциям на разные пакеты.

Также большие многострочные кодовые константы лучше убрать из кода функций - делает код более читаемым.

Не стоит пока делать больше чем требуется(хранение времени обновления метрик).
Еще бы рекомендовал все-таки использовать единый код хранения метрик, раз он выполняет одинаковые функции.

2023-06-07 11:39 UTC, valentinsoe commented on cmd/server/handlers.go
> +	<html><head><title>Metrics Index</title></head>
Для лучше читаемости кода, такие длинные строковые константы лучше выносить за пределы кода функций.

2023-06-07 11:39 UTC, valentinsoe commented on cmd/server/handlers.go
> +package main
В пакете main обычно принято иметь только инициализацию приложения. Все хендлеры, роутеры и конфиги лучше унести в раздельные пакеты внутренней реализации.

2023-06-07 11:39 UTC, valentinsoe commented on cmd/agent/main.go
> +	r = rand.New(rand.NewSource(rand.Int63()))
Зачем мы отдельно инициализирует rand, а не используем стандартный?

2023-06-07 11:39 UTC, valentinsoe commented on internal/agent/reporters.go
> +	c := http.Client{Timeout: time.Duration(1) * time.Second}
Клиент не обязательно инициализировать каждый раз.
Можно сделать это однажды при создании репортера.

2023-06-07 11:39 UTC, valentinsoe commented on internal/agent/reporters.go
> +// PrintReporter is a test reporter to stdout
Если бы был интерфейс Reporter, то можно было бы иметь две его реализации и подменять их на стадии инициализации.

2023-06-07 11:59 UTC, freepaddler commented on internal/store/store.go
> +// TODO: question
логично, не имеет смысла тогда, согласен

2023-06-07 12:01 UTC, freepaddler commented on cmd/server/main.go
> +	//mux := http.NewServeMux()
+

2023-06-07 12:06 UTC, freepaddler commented on internal/agent/stats.go
> +	prev  int64
мы его храним, чтобы считать инкремент в таком случае:

отправка А подвисла
отправка Б прошла
отправка А, наконец, тоже прошла

в таком случае мы не должны обновлять значение prev 

но вообще, конечно, глупость, потому что на сервере такая проверка не делается :(
но при распараллеливании процессов сбора и отправки это нужно будет как-то решать
пока уберу

2023-06-07 12:45 UTC, valentinsoe commented on internal/agent/stats.go
> +	prev  int64
Без синхронизации это пока лишено смысла. А с многопоточностью и синхронизацией тоже такой подходит не даст эффекта.
Отправка Б уже изменит prev и если до отправки А что-то накопится, то оно посчитается об новый prev.
Или отправка Б уже занулит текущее значение. И если до отправки А что-то накопится, то именно оно и отправится.

Результат тот же, кода больше:)

2023-06-07 12:52 UTC, valentinsoe commented on internal/store/store.go
> +var _ Storage = (*MemStorage)(nil)
Интересно. Но если memStorage на будет сответствовать интерфейсу, то IDE это подсветит в том месте, где ты реально пытаешься его использовать как интерфейс.

2023-06-08 03:25 UTC, freepaddler commented on internal/agent/reporters.go
> +// PrintReporter is a test reporter to stdout
так у меня же так и есть, просто  раскомментировать этот репортер?

2023-06-09 18:42 UTC, valentinsoe requested changes
Спасибо что исправил замечания. Все хорошо.
Осталось пара мелких недочетов и один недочет-вопрос.

2023-06-09 18:42 UTC, valentinsoe commented on internal/agent/config/config.go
> +		defaultHTTPTimeout,
Какой будет таймаут по умолчанию(если не передать параметры и не задать переменную окружения)?

2023-06-09 18:42 UTC, valentinsoe commented on internal/agent/interfaces.go
> +	// Report sends metric and returns true on success report
Комментарий не совсем честен - Report() ничего не возвращает нам.

2023-06-09 18:42 UTC, valentinsoe commented on internal/agent/reporter/http.go
> +		defer resp.Body.Close()
Не совсем удачный подход использовать defer в цикле.
Самый типичный паттерн использования defer - освобождение ресурсов. Но если мы вызываем его в цикле, то ресурсы будут освобождены не в конце итерации цикла, а только в конце функции.
Что с этим можно делать? - Завернуть тело цикла в функции(можно даже анонимную)

2023-06-09 18:42 UTC, valentinsoe commented on internal/server/handler/http.go
> +func NewHTTPHandlers(srv store.Storage) *HTTPHandlers {
Осталось наверное от сервера. Не самое удачное название для параметра storage.

2023-06-10 12:54 UTC, freepaddler commented on internal/agent/config/config.go
> +		defaultHTTPTimeout,
о! это отличный вопрос
я много думал :)
ну, он будет 1 наносекунду, но http-репортере при инициализации клиента он приводится к секундам
думал сделать uint... но увидел что есть прямо duration.
есть рекомендации - как передавать время как продолжительность? int, timeparse, duration?

2023-06-10 13:06 UTC, freepaddler commented on internal/agent/reporter/http.go
> +		defer resp.Body.Close()
ой, действительно, очень ценное замечание. анономная функция очень хорошо вписывается, потому что есть условия выхода.

2023-06-11 07:11 UTC, freepaddler commented on internal/agent/config/config.go
> +		defaultHTTPTimeout,
добавил лимиты, валидацию

2023-06-13 13:45 UTC, valentinsoe approved these changes

2023-06-13 13:46 UTC, merged